name = "Baseline White Agent (placeholder)"
url  = "http://localhost:8011"
launcher_url = "http://localhost:9011"
description = "Placeholder endpoint that returns 501 while the green agent replays scripted turns."
capabilities = ["a2a","tools"]
entrypoint = "uvicorn werewolf.agent_white:app --host 0.0.0.0 --port 8011"
